### ISSUE TITLE
大佬能说一下build和返回值和create的请求内容，有哪些地方需要修改吗？

### ISSUE THREAD

**Issue by gyhua96** [gxh27954/damai_requests#17]
大佬，我现在拿到了build的响应内容，能说一下修改哪些内容之后传给create请求吗？

**Comment by gxh27954** [comment]
> 大佬，我现在拿到了build的响应内容，能说一下修改哪些内容之后传给create请求吗？

直接抓一个create的包？内容比较多需要处理的

**Comment by gyhua96** [comment]
create接口一直提示"FAIL_SYS_ILEGEL_SIGN::非法请求签名"，请问你有遇到这个情况吗？create的请求头是直接使用build的，还是要重新生成？我试了都不行

**Comment by gxh27954** [comment]
> create接口一直提示"FAIL_SYS_ILEGEL_SIGN::非法请求签名"，请问你有遇到这个情况吗？create的请求头是直接使用build的，还是要重新生成？我试了都不行

要重新生成，因为x-sign之类的加密信息不一样了，你的create里的data可能处理的不争气

**Comment by gyhua96** [comment]
生成create的请求头的时候，与build接口对比，除了修改apiName和data，还要其它地方需要修改吗？
json请求体在进行base64编码的时候，换行是怎么处理的呢？
create的json请求已经对比过几次了，应当是没有问题的。

**Comment by gyhua96** [comment]
已经成了，是我自己逻辑搞错了，传错了值，现在ok了
方便加个联系方式吗？交流一下

**Comment by gxh27954** [comment]
> 已经成了，是我自己逻辑搞错了，传错了值，现在ok了 方便加个联系方式吗？交流一下

readme里有联系方式

**Comment by wj61972874** [comment]
> > 已经成了，是我自己逻辑搞错了，传错了值，现在ok了 方便加个联系方式吗？交流一下
> 
> readme里有联系方式

找不到该联系人啊

**Comment by gxh27954** [comment]
> > > 已经成了，是我自己逻辑搞错了，传错了值，现在ok了 方便加个联系方式吗？交流一下
> > 
> > 
> > readme里有联系方式
> 
> 找不到该联系人啊

base64解码一下

**Comment by gyhua96** [comment]
all done.
