### ISSUE TITLE
BUG交流

### ISSUE THREAD

**Issue by modcoco** [gxh27954/damai_requests#2]
![image](https://github.com/gxh27954/damai_requests/assets/142997740/3da0f470-e28c-4197-8d8f-8501f50304bd)
自己写的，经历和你很相似，也有类似问题，不过不太稳定，可以交流一下，邮件

**Comment by modcoco** [comment]
很大概率是号的问题

**Comment by gxh27954** [comment]
> 很大概率是号的问题

你的不太稳定是啥问题

**Comment by modcoco** [comment]
订单提交后是有极高概率被拒绝的，返回F-10012-01-16-001应该是被ali的mtee标记为风险过滤了

**Comment by gxh27954** [comment]
> 订单提交后是有极高概率被拒绝的，返回F-10012-01-16-001应该是被ali的mtee标记为风险过滤了

原来如此，我刚刚注册了个新号，也出现一样的报错，可能是设备问题了

**Comment by modcoco** [comment]
你用的什么设备

**Comment by gxh27954** [comment]
> 你用的什么设备

注册账号用的自己的iphone，hook用的模拟器

**Comment by modcoco** [comment]
不好找到关键点过风险过滤，还得多实践找问题

**Comment by gxh27954** [comment]
> 不好找到关键点过风险过滤，还得多实践找问题

是啊，但是实践有点不好操作了，只有热门的开抢了之后才能调试。那种大把票的，就一切正常

**Comment by modcoco** [comment]
真的没什么思路了，这个风控得怎么避免，ta这服务真的能在毫秒级判断人机行为感觉不现实，感觉根据账号的历史行为综合+IP做的

**Comment by modcoco** [comment]
去调研某鱼平台的老黄，一些老黄使用他们的工具去拿热门的确实可以拿到

**Comment by gxh27954** [comment]
> 去调研某鱼平台的老黄，一些老黄使用他们的工具去拿热门的确实可以拿到

你那边遇到的也是一样的问题吗，你还有其他问题未解决不

**Comment by modcoco** [comment]
暂时没有其他问题

**Comment by modcoco** [comment]
你最近有什么进展吗

**Comment by gxh27954** [comment]
> 你最近有什么进展吗

无，这两天没有继续研究

**Comment by modcoco** [comment]
> 你已经解决了吗
最近有空在用rust重构代码，对了，我想咨询一下，你监控票用的那个接口。前几天我发现我的控票断断续续的

**Comment by gxh27954** [comment]
> > 你已经解决了吗
> > 最近有空在用rust重构代码，对了，我想咨询一下，你监控票用的那个接口。前几天我发现我的控票断断续续的

我这边一直老样子，还是热门的抢不了
用的这个接口
https://detail.damai.cn/subpage?itemId=%s&dataId=%s&dataType=2&apiVersion=2.0&dmChannel=damai_app

**Comment by modcoco** [comment]
嗯嗯，我没用app的，我嫌监控请求太频繁了

**Comment by modcoco** [comment]
这个接口稳定吗，应该得要签名吧

**Comment by modcoco** [comment]
这个接口稳定吗，应该得要签名吧
