### ISSUE TITLE
由详情页向订单页面发请求时出现”您选购的商品信息已过期，请重新查询“这是为什么

### ISSUE THREAD

**Issue by Googasy** [gxh27954/damai_requests#7]

**Comment by gxh27954** [comment]
> _No description provided._

等开售了再请求就有了

**Comment by Googasy** [comment]
我尝试的是五月天重庆的，他已经开售了，但无货现在

**Comment by gxh27954** [comment]
> 我尝试的是五月天重庆的，他已经开售了，但无货现在

那应该是官方关闭了购买通道

**Comment by Googasy** [comment]
谢谢大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月30日(周三) 下午3:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gxh27954/damai_requests] 由详情页向订单页面发请求时出现”您选购的商品信息已过期，请重新查询“这是为什么 (Issue #7)




  
我尝试的是五月天重庆的，他已经开售了，但无货现在
  
那应该是官方关闭了购买通道
